spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/inventory?useSSL=true
    username: root
    password: "0109"
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.kade2021inventorylingduanhui.inventorytest.pojo
