spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/inventory?useSSL=true&charsetEncoding=utf-8
    username: root
    password: 12345
  redis:
    host: localhost
    port: 6379
    database: 0
    password: 12345

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kade2021inventory.*.pojo


